//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wintogo.MultiLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceLang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceLang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("wintogo.MultiLanguage.ResourceLang", typeof(ResourceLang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VHD模式说明.TXT.
        /// </summary>
        public static string FileName_VHD_Dynamic {
            get {
                return ResourceManager.GetString("FileName_VHD_Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请不要将程序放入中文文件夹运行。.
        /// </summary>
        public static string IsChinaMsg {
            get {
                return ResourceManager.GetString("IsChinaMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 镜像文件应用失败！.
        /// </summary>
        public static string Msg_ApplyError {
            get {
                return ResourceManager.GetString("Msg_ApplyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 引导文件写入出错！boot文件夹不存在！.
        /// </summary>
        public static string Msg_BCDError {
            get {
                return ResourceManager.GetString("Msg_BCDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本机系统需要Windows 10 1709或更高版本以支持可移动磁盘 UEFI启动部署。.
        /// </summary>
        public static string Msg_Below1709 {
            get {
                return ResourceManager.GetString("Msg_Below1709", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitlocker仅在勾选UEFI+GPT或UEFI+MBR的传统模式下可用。.
        /// </summary>
        public static string Msg_BitlockerUnusable {
            get {
                return ResourceManager.GetString("Msg_BitlockerUnusable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件写入出错！请检查写入过程是否中断！.
        /// </summary>
        public static string Msg_bootmgrError {
            get {
                return ResourceManager.GetString("Msg_bootmgrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择FFU文件存储位置.
        /// </summary>
        public static string Msg_ChooseFFU {
            get {
                return ResourceManager.GetString("Msg_ChooseFFU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择镜像文件！.
        /// </summary>
        public static string Msg_chooseinstallwim {
            get {
                return ResourceManager.GetString("Msg_chooseinstallwim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择可移动设备.
        /// </summary>
        public static string Msg_chooseud {
            get {
                return ResourceManager.GetString("Msg_chooseud", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此操作将会清除移动磁盘所有分区的所有数据，确认？.
        /// </summary>
        public static string Msg_ClearPartition {
            get {
                return ResourceManager.GetString("Msg_ClearPartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作完成！.
        /// </summary>
        public static string Msg_Complete {
            get {
                return ResourceManager.GetString("Msg_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认您所选择的.
        /// </summary>
        public static string Msg_ConfirmChoose {
            get {
                return ResourceManager.GetString("Msg_ConfirmChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序将会重启，确认继续？.
        /// </summary>
        public static string Msg_ConfirmRestart {
            get {
                return ResourceManager.GetString("Msg_ConfirmRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制文件中...大约需要10分钟~1小时，请耐心等待！\n.
        /// </summary>
        public static string Msg_Copy {
            get {
                return ResourceManager.GetString("Msg_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序删除临时文件出错！可重启程序或重启电脑重试！\n.
        /// </summary>
        public static string Msg_DeleteTempError {
            get {
                return ResourceManager.GetString("Msg_DeleteTempError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 盘，容量.
        /// </summary>
        public static string Msg_Disk_Space {
            get {
                return ResourceManager.GetString("Msg_Disk_Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 优盘容量小于VHD设定大小，请修改设置！.
        /// </summary>
        public static string Msg_DiskSpaceError {
            get {
                return ResourceManager.GetString("Msg_DiskSpaceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 可移动磁盘容量不足16G，继续写入可能会导致程序出错！您确定要继续吗？.
        /// </summary>
        public static string Msg_DiskSpaceWarning {
            get {
                return ResourceManager.GetString("Msg_DiskSpaceWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请安装.NET Framework 4.6.1或更高版本！.
        /// </summary>
        public static string Msg_DotnetVersionError {
            get {
                return ResourceManager.GetString("Msg_DotnetVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 如果您不清楚您在做什么，请立即停止操作！.
        /// </summary>
        public static string Msg_DoWhat {
            get {
                return ResourceManager.GetString("Msg_DoWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误！.
        /// </summary>
        public static string Msg_error {
            get {
                return ResourceManager.GetString("Msg_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此系统不支持ESD文件处理！.
        /// </summary>
        public static string Msg_ESDError {
            get {
                return ResourceManager.GetString("Msg_ESDError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 操作失败！.
        /// </summary>
        public static string Msg_Failure {
            get {
                return ResourceManager.GetString("Msg_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序文件损坏，请重新下载程序！.
        /// </summary>
        public static string Msg_FileBroken {
            get {
                return ResourceManager.GetString("Msg_FileBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是将要写入的优盘或移动硬盘.
        /// </summary>
        public static string Msg_FormatTip {
            get {
                return ResourceManager.GetString("Msg_FormatTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此分区将会被格式化，不可恢复，您确定要继续吗？.
        /// </summary>
        public static string Msg_FormatWarning {
            get {
                return ResourceManager.GetString("Msg_FormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚拟光驱加载失败，请手动加载，之后选择install.wim.
        /// </summary>
        public static string Msg_ImageError {
            get {
                return ResourceManager.GetString("Msg_ImageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此类优盘使用传统模式可能无法启动，确认继续？.
        /// </summary>
        public static string Msg_Legacywarning {
            get {
                return ResourceManager.GetString("Msg_Legacywarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 盘符V不能被占用！.
        /// </summary>
        public static string Msg_LetterV {
            get {
                return ResourceManager.GetString("Msg_LetterV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 否.
        /// </summary>
        public static string Msg_No {
            get {
                return ResourceManager.GetString("Msg_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFS文件流异常\n请放心，此错误不影响正常使用.
        /// </summary>
        public static string Msg_ntfsstream {
            get {
                return ResourceManager.GetString("Msg_ntfsstream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTFS分区UEFI支持.
        /// </summary>
        public static string Msg_NtfsUefiSupport {
            get {
                return ResourceManager.GetString("Msg_NtfsUefiSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此选项仅在非UEFI模式下有效！.
        /// </summary>
        public static string Msg_OnlyNonUefi {
            get {
                return ResourceManager.GetString("Msg_OnlyNonUefi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 分区错误.
        /// </summary>
        public static string Msg_PartitionError {
            get {
                return ResourceManager.GetString("Msg_PartitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名错误.
        /// </summary>
        public static string Msg_RenameError {
            get {
                return ResourceManager.GetString("Msg_RenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您勾选了重新分区，优盘或移动硬盘上的所有文件将被删除！\n注意是整个磁盘，不是一个分区！.
        /// </summary>
        public static string Msg_Repartition {
            get {
                return ResourceManager.GetString("Msg_Repartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 不格式化不能与“重新分区”或“UEFI+GPT”或“UEFI+MBR”选项共存。.
        /// </summary>
        public static string Msg_SelectBothNoformatAndRepartition {
            get {
                return ResourceManager.GetString("Msg_SelectBothNoformatAndRepartition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示！.
        /// </summary>
        public static string Msg_Tip {
            get {
                return ResourceManager.GetString("Msg_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请确认优盘信息无误.
        /// </summary>
        public static string Msg_TwiceConfirm {
            get {
                return ResourceManager.GetString("Msg_TwiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 请选择优盘根目录.
        /// </summary>
        public static string Msg_UDRoot {
            get {
                return ResourceManager.GetString("Msg_UDRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此优盘不支持UEFI模式\n只有 Fixed Disk格式支持\n详情请看论坛说明！.
        /// </summary>
        public static string Msg_UefiError {
            get {
                return ResourceManager.GetString("Msg_UefiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您所选择的是UEFI模式，此模式将会格式化您的整个移动磁盘！\n注意是整个磁盘！！！\n程序将会删除所有优盘分区！.
        /// </summary>
        public static string Msg_UefiFormatWarning {
            get {
                return ResourceManager.GetString("Msg_UefiFormatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 若无弹出窗口，则当前程序已是最新版本！.
        /// </summary>
        public static string Msg_UpdateTip {
            get {
                return ResourceManager.GetString("Msg_UpdateTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VHD模式下BCDBOOT执行出错！.
        /// </summary>
        public static string Msg_VHDBcdbootError {
            get {
                return ResourceManager.GetString("Msg_VHDBcdbootError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VHD文件创建出错！.
        /// </summary>
        public static string Msg_VHDCreationError {
            get {
                return ResourceManager.GetString("Msg_VHDCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您创建的VHD为动态大小VHD，实际VHD容量：.
        /// </summary>
        public static string Msg_VHDDynamicSize {
            get {
                return ResourceManager.GetString("Msg_VHDDynamicSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在VHD系统启动后将自动扩充为实际容量。请您在优盘留有足够空间确保系统正常启动！.
        /// </summary>
        public static string Msg_VHDDynamicSize2 {
            get {
                return ResourceManager.GetString("Msg_VHDDynamicSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚拟硬盘文件名不能包含中文或空格，请修改！.
        /// </summary>
        public static string Msg_VHDNameIllegal {
            get {
                return ResourceManager.GetString("Msg_VHDNameIllegal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 虚拟硬盘模式制作成功率较低，启动兼容性较差，不推荐使用。\n是否继续选择？.
        /// </summary>
        public static string Msg_VHDXWarning {
            get {
                return ResourceManager.GetString("Msg_VHDXWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 警告！.
        /// </summary>
        public static string Msg_warning {
            get {
                return ResourceManager.GetString("Msg_warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WIM文件信息获取失败\n将按WIN8系统安装.
        /// </summary>
        public static string Msg_wiminfoerror {
            get {
                return ResourceManager.GetString("Msg_wiminfoerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 处理WIN7 USB启动时出现问题.
        /// </summary>
        public static string Msg_win7usberror {
            get {
                return ResourceManager.GetString("Msg_win7usberror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在写入....
        /// </summary>
        public static string Msg_WriteProcessing {
            get {
                return ResourceManager.GetString("Msg_WriteProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正在写入，您确定要取消吗？.
        /// </summary>
        public static string Msg_WritingAbort {
            get {
                return ResourceManager.GetString("Msg_WritingAbort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP系统不支持此操作.
        /// </summary>
        public static string Msg_XPNotCOMP {
            get {
                return ResourceManager.GetString("Msg_XPNotCOMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XP系统不支持UEFI模式写入.
        /// </summary>
        public static string Msg_XPUefiError {
            get {
                return ResourceManager.GetString("Msg_XPUefiError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 是.
        /// </summary>
        public static string Msg_Yes {
            get {
                return ResourceManager.GetString("Msg_Yes", resourceCulture);
            }
        }
    }
}
